library_managment_system/library/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home_page, name='home_page'),
]

library_managment_system/library_managment_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('library.urls')),
    path('user/', include('user.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

library_managment_system/user/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home_page, name='home'),
    path('register/', views.register_page, name='register_page'),
    path('login/', views.login_page, name='login_page'),
    path('logout/', views.logout_page, name='logout_page'),
    path('book/<int:book_id>/', views.book_page, name='book_page'),
    path('book/create/', views.create_book_page, name='create_book_page'),
]

library_managment_system/library/models.py
from django.db import models

# Create your models here.

library_managment_system/user/models.py
from django.db import models
from django.contrib.auth.models import User

class Book(models.Model):

    categories = [('ACT', 'Action'), ('ROM', 'Romance'), ('MYS', 'Mystries'), ('THR', 'Thrill'), ('HOR', 'Horror')]

    book_name = models.CharField(max_length=100)
    cover_image = models.ImageField(upload_to='covers/')
    issued_date = models.DateField()
    auther = models.CharField(max_length=50)
    category = models.CharField(max_length=3, choices=categories, default='HOR')

    def __str__(self):
        return self.book_name

# class Member(models.Model):

#     user = models.ForeignKey(User, on_delete=models.CASCADE)
#     email = models.EmailField(unique=True)

library_managment_system/user/forms.py
from django import forms
from .models import Book
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

class Book_Form(forms.ModelForm):

    class Meta:

        model = Book
        fields = ('book_name', 'cover_image', 'issued_date', 'auther', 'category')

class Member_Form(UserCreationForm):

    class Meta:

        model = User
        fields = ('username', 'email', 'password1', 'password2')

class Member_login_Form(AuthenticationForm):

    class Meta:

        model = User
        fields = ('username', 'password1', 'password2')

library_managment_system/library/views.py
from django.shortcuts import render

# Create your views here.
def home_page(request):

    return render(request, 'home_page.html')

library_managment_system/user/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import Member_Form, Member_login_Form, Book_Form
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import AuthenticationForm
from .models import Book

def home_page(request):

    books = Book.objects.all()
    return render(request, "home_page.html", {'books': books})

def book_page(request, book_id):

    book = get_object_or_404(Book, pk=book_id)

    return render(request, 'book_page.html', { 'book': book })

def register_page(request):

    if request.method == 'POST':

        form = Member_Form(request.POST)
        if form.is_valid():

            user = form.save()
            login(request, user)
            return redirect('home_page')

    return render(request, "register_page.html", { 'form': Member_Form })

def login_page(request):

    if request.POST:

        form = Member_login_Form(request, data=request.POST)
        if form.is_valid():

            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)

            if user is not None:

                login(request, user)
                return redirect('home_page')
            

    form = Member_login_Form()
        

    return render(request, "login_page.html", {'form': form})

def logout_page(request):


    logout(request)

    return redirect("home_page")

def create_book_page(request):

    if request.method == 'POST':

        form = Book_Form(request.POST, request.FILES)

        if form.is_valid():

            form.save()

            return redirect('home_page')

    form = Book_Form()

    return render(request, 'create_book_page.html', { 'form': form })

library_managment_system/library/templates/home_page.html
{% extends 'layouts.html' %}

{% block content %}
    {{user}}
{% endblock %}

library_managment_system/templates/layouts.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/layouts.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css" integrity="sha512-Evv84Mr4kqVGRNSgIGL/F/aIDqQb7xQ2vcrdIwxfjThSH8CSR7PBEakCr51Ck+w+/U6swU2Im1vVX0SVk9ABhg==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    {% block style %}
        <!-- CSS will goes here -->
    {% endblock %}

    <title>{% block title %} Library Management System {% endblock %}</title>
</head>
<body>
    {% block navbar %}
        <nav class="navbar">
            <div class="logo">Library</div>
            <ul class="nav-links">
                <li><a href="#">Home</a></li>
                <li><a href="#">Books</a></li>
                <li><a href="#">Categories</a></li>
                <li><a href="#">Contact</a></li>
                {% if user.is_authenticated %}
                    <li><a href="{% url 'logout_page' %}">Logout</a></li>
                {% else %}
                    <li><a href="{% url 'login_page' %}">Login</a></li>
                {% endif %}
                <li><button class="dark-mode-toggle"><i class="fa-solid fa-cloud-sun"></i></button></li>
            </ul>
            <div class="hamburger"><i class="fa-solid fa-bars"></i></div>
        </nav>
    {% endblock %}
    {% block content %}
        
    {% endblock %}
    <script>
        document.addEventListener("DOMContentLoaded", () => {
            const hamburger = document.querySelector(".hamburger");
            const navLinks = document.querySelector(".nav-links");
            const darkModeToggle = document.querySelector(".dark-mode-toggle");

            if (localStorage.getItem("darkMode") == "on") {
                document.body.classList.toggle("dark-mode");
            }
            
            hamburger.addEventListener("click", () => {
                navLinks.classList.toggle("active");
            });
            
            darkModeToggle.addEventListener("click", () => {
                document.body.classList.toggle("dark-mode");
                localStorage.setItem("darkMode", "on");
            });
        });
    </script>
</body>
</html>

library_managment_system/user/templates/book_page.html
{% extends 'layouts.html' %}
{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static 'css/book_page.css' %}">
{% endblock %}

{% block title %}
    {{ book.book_name }} - Book By {{ book.auther }}
{% endblock %}

{% block content %}
<div class="container">
    <img src="{{ book.cover_image.url }}" alt="Book Cover" class="book-cover">
    <div class="book-info">
        <p class="book-title">{{ book.book_name }}</p>
        <p class="book-author">by {{book.auther}}</p>
        <p class="book-genre">Genre: {{book.get_category_display}}</p>
    </div>
    <div class="reviews">⭐⭐⭐⭐⭐<br/>A masterpiece! Absolutely loved it!"</div>
</div>
{% endblock %}

library_managment_system/user/templates/create_book_page.html
{% extends 'layouts.html' %}

{% block style %}
    <link rel="stylesheet" href="{% static 'css/user_register_page.css' %}">
{% endblock %}

{% block content %}
    <form action="{% url 'create_book_page' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        <button type="submit">Add Book</button>
    </form>    
{% endblock %}

library_managment_system/user/templates/home_page.html
{% extends 'layouts.html' %}
{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static 'css/home_page.css' %}">
{% endblock %}

{% block content %}
    <div class="container">
        {% for book in books %}
            <div class="book-card">
                <img src="{{ book.cover_image.url }}" alt="Book Cover" class="book-cover">
                <div class="book-info">
                    <h2 class="book-title"><a href="/user/book/{{book.id}}/">{{book.book_name}}</a></h2>
                    <p class="book-author">by {{book.auther}}</p>
                    <p class="book-genre">Genre: {{book.get_category_display}}</p>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

library_managment_system/user/templates/login_page.html
{% extends 'layouts.html' %}

{% block style %}
    <link rel="stylesheet" href="{% static 'css/user_register_page.css' %}">
{% endblock %}

{% block title %}
    Login Page
{% endblock %}

{% block navbar %}
    <!-- It should be empty to not show a navbar -->
{% endblock %}

{% block content %}
    <form action="{% url 'login_page' %}", method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
{% endblock %}

library_managment_system/user/templates/register_page.html
{% extends 'layouts.html' %}

{% block style %}
    <link rel="stylesheet" href="{% static 'css/user_register_page.css' %}">
{% endblock %}

{% block title %}
    Register Page
{% endblock %}

{% block navbar %}
    <!-- It should be empty to not show a navbar -->
{% endblock %}

{% block content %}
    <form action="{% url 'register_page' %}", method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
{% endblock %}